Settings Version: 1.0.1
# local_settings = join(expanduser("~"), ".temperatuer_control", "settings.yml")

Data Folder: ../../../data/temperature
# Save the info from Log Dock to this file in Data Folder
Log File: temperature.log

Temperature Columns:
  - "date"
  - "time"
  - "T"
  - "PresetT"
  - "Qms signal"
  - "Cathode Box T"
  - "p"
  - "i"
  - "d"

# ================================================
#
# 4 channel 24-Bit Temperature Input Module : NI-9211
# https://www.ni.com/ja-jp/support/model.ni-9211.html
#
# ================================================

NI9211:
  Tc0:
    Channel: 0
    Description: "Membrane Temperature"
    Type: Thermocouple
    Thermocouple Type: K
    Sampling Rate: 10
  Tc1:
    Channel: 1
    Description: "Cathode Box Temperature"
    Type: Thermocouple
    Thermocouple Type: K
    Sampling Rate: 10

Sampling Time: 0.1
# ================================================
#
# GPIO Board : Adafruit FT232H
# https://www.adafruit.com/product/2264
# https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows
# https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/pinouts
# https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/gpio
#
# ================================================
# GPIO Board for control relay circuit of the membrane heater

Max Temperature: 1200

Duty Cycle: 0.01

FT232H:
  Heater Output:
    Pin: c0
    Description: "Membrane Heater Output"
  Sync Input:
    Pin: c1
    Description: "Signal Input for time synchronization with Raspberry Pi"
